# Generated by Django 4.0.4 on 2023-09-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_clientsystem_is_assistant'),
        ('inventory', '0003_workdishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_research', to='clients.clientsystem', verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_research', to='clients.clientsystem', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Исследование студента',
                'verbose_name_plural': 'Исследование студента',
            },
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Запрос студента')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='research.research', verbose_name='Исследование')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='clients.clientsystem', verbose_name='Студент')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='inventory.work', verbose_name='Эксперимент')),
            ],
            options={
                'verbose_name': 'Запрос студента на эксперимент',
                'verbose_name_plural': 'Запросы студента на эксперименты',
            },
        ),
    ]
