# Generated by Django 4.0.4 on 2023-09-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentworkreagents',
            options={'verbose_name': 'Реактивы студента', 'verbose_name_plural': 'Реактивы студента'},
        ),
    ]
