# Generated by Django 4.0.4 on 2023-10-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentworkreagents_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentworkreagents',
            name='real_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактически взято'),
        ),
    ]
